PRODUCT_VERSION_MAJOR = 0
PRODUCT_VERSION_MINOR = 1
PRODUCT_VERSION_MAINTENANCE = 0

JCROM_VERSION := B2JC-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(shell LANG=en date -u +%Y%m%d)


